"""Prompt-injection and PII guard added by Lineaje UnifAI remediation.

One shared module per service: remediation fixes import it instead of adding
their own sanitizers, so every route applies the same rules. Standard library
only; Python 3.8+.

* ``sanitize_prompt(text)``: removes prompt-injection spans from untrusted text
  (user input, uploaded or retrieved content) before it reaches a model. Only
  the matched span is replaced; the rest of the text, its newlines and layout
  are kept.
* ``find_prompt_attacks(text)``: the attack categories found, for code that
  refuses input instead of cleaning it.
* ``redact_pii(text, categories)``: masks the personal data a policy defines
  (its ``runtime.routine.params.categories``, per region) in text sent to a
  model, a log, a user or an external service.
* ``mask_pii(text, categories)``: the same detection as ``redact_pii``, shown in
  masked form for text displayed to a user: an identifier (SSN, card, account)
  keeps its last 4 digits (``***-**-6789``), any other value becomes
  ``<masked:label>`` (``<masked:phone>``).
* ``sanitize_messages(messages)``: ``sanitize_prompt`` on the user/tool turns of
  a chat message list (string content and text parts).
* ``remove_suspicious_content(text)``: uploaded or fetched file content with shell
  commands (alias, rg/ripgrep, curl, wget, rm, echo > file, dd, git, tar, chmod, chown,
  fsck, mkfs, shred, eval, source, export), also when base64-encoded or written in
  leetspeak, replaced by ``<suspicious_content_removed>``; ``find_shell_commands(text)``
  lists them.
* ``find_code_execution(text)``: the dynamic code-execution primitives found in
  model output (eval, exec, os.system, subprocess with shell=True, JS eval /
  Function / child_process, shell eval, piping a download into a shell), for code
  that validates an answer before it is executed or shown.

Never apply these to identifiers or lookup keys (user ids, file names, document
ids): those must reach their service unchanged.
"""
import base64
import binascii
import re

__all__ = ["sanitize_prompt", "find_prompt_attacks", "redact_pii", "mask_pii", "sanitize_messages",
           "unsupported_pii_categories", "find_code_execution", "remove_suspicious_content",
           "find_shell_commands"]
__version__ = "2.4.0"

# UNIFAI-GUARD owner="Lineaje UnifAI": generated by UnifAI remediation scans; do not edit.
# Scans read UNIFAI_GUARD_MANIFEST (without running this file) to reuse this module instead
# of adding another guardrail, and ship a newer version that only adds routines when a
# policy needs one listed nowhere below. Keys are the policies' runtime.routine.id values.
UNIFAI_GUARD_MANIFEST = {
    "owner": "Lineaje UnifAI",
    "version": "2.4.0",
    "routines": {
        "sanitize_prompt_injection": ["sanitize_prompt", "find_prompt_attacks", "sanitize_messages",
                                      "remove_suspicious_content", "find_shell_commands"],
        "mask_pii": ["redact_pii", "mask_pii"],
        "mask_pii_and_secrets": ["redact_pii", "mask_pii"],
        "validate_llm_output": ["find_code_execution"],
    },
}

# --- prompt injection -------------------------------------------------------

_Q = r"(?:all|any|every|the|your|my|of\s+the)?\s*"
_PHRASES = (
    ("instruction_override", re.compile(
        r"\b(?:ignore|disregard|forget|override|bypass|skip)\s+" + _Q
        + r"(?:(?:previous|prior|above|earlier|preceding|original|existing|safety|system)\s+)+"
        r"(?:instructions?|rules|guidelines|prompts?|directions|directives|constraints)\b"
        r"|\bforget\s+everything\s+(?:above|before|you\s+were\s+told)\b"
        r"|\bsystem\s+override\b", re.I)),
    ("role_hijack", re.compile(
        r"\byou\s+are\s+now\s+(?:in\s+)?(?:an?\s+)?"
        r"(?:dan|unrestricted|unfiltered|jailbroken|evil|developer\s+mode|admin(?:istrator)?\s+mode|god\s+mode)\b"
        r"|\bact\s+as\s+(?:an?\s+)?(?:unrestricted|unfiltered|jailbroken|uncensored)\s+(?:ai|model|assistant|chatbot)\b"
        r"|\b(?:developer|jailbreak|god)\s+mode\s+(?:enabled|activated|on)\b", re.I)),
    ("prompt_exfiltration", re.compile(
        r"\b(?:reveal|show|print|display|output|repeat|leak|dump|tell\s+me)\s+(?:me\s+)?"
        r"(?:all\s+|your\s+|the\s+)*(?:full\s+|entire\s+|hidden\s+|initial\s+|original\s+|secret\s+)?"
        r"(?:system\s+(?:prompts?|instructions|messages?)|initial\s+prompts?|hidden\s+instructions)\b", re.I)),
    ("data_exfiltration", re.compile(
        r"\b(?:reveal|list|dump|show|give\s+me)\s+(?:me\s+)?all\s+(?:the\s+)?"
        r"(?:confidential|secret|private|sensitive)\s+(?:information|data)\b"
        r"|\b(?:user\s+passwords|api\s+keys|access\s+tokens|private\s+keys)\b"
        r"|\bprovide\s+unrestricted\s+access\b", re.I)),
)
_EXFIL_VERB = re.compile(r"\b(?:list|reveal|dump|show|give|send|print|output|leak)\b", re.I)

_HIDDEN_HTML = re.compile(
    r"<(?P<tag>[a-z][a-z0-9]*)\b[^>]*?(?:\shidden\b|style\s*=\s*[\"'][^\"']*"
    r"(?:display\s*:\s*none|visibility\s*:\s*hidden|font-size\s*:\s*0)[^\"']*[\"']"
    r"|class\s*=\s*[\"'][^\"']*\b(?:hidden|invisible|sr-only)\b[^\"']*[\"'])[^>]*>"
    r".*?</(?P=tag)\s*>", re.I | re.S)
_MARKDOWN_IMAGE_EXFIL = re.compile(r"!\[[^\]\n]*\]\(\s*https?://[^)\s]*\?[^)\s]*\)", re.I)
_SHELL = re.compile(
    r"\b(?:bash|sh|zsh|ksh|powershell|pwsh|cmd(?:\.exe)?)\s+(?:-c|/c|-command)\s+\S[^\n]*"
    r"|\b(?:curl|wget)\s+[^\n|]*\|\s*(?:ba|z)?sh\b"
    r"|\brm\s+-rf\s+/\S*", re.I)
_CHAT_TOKENS = re.compile(r"<\|[a-z_]{2,20}\|>|\[/?INST\]|<</?SYS>>", re.I)
_BASE64 = re.compile(r"(?<![A-Za-z0-9+/=])[A-Za-z0-9+/]{20,}={0,2}(?![A-Za-z0-9+/=])")

_LEET = str.maketrans({"0": "o", "1": "i", "3": "e", "4": "a", "5": "s", "7": "t", "@": "a", "$": "s"})
_SPACED = re.compile(r"(?<!\S)(?:[A-Za-z0-9@$]\s){3,}[A-Za-z0-9@$](?!\S)")


def _normalized(text):
    """(normalized text, index map): leetspeak folded, single-letter spacing removed.

    Every character of the normalized text maps back to its index in *text*, so
    a match removes exactly the original span."""
    drop = set()
    for m in _SPACED.finditer(text):
        drop.update(i for i in range(m.start(), m.end()) if text[i].isspace())
    chars, index = [], []
    for i, ch in enumerate(text):
        if i not in drop:
            chars.append(ch)
            index.append(i)
    return "".join(chars).translate(_LEET), index


def _phrase_spans(text):
    spans = []
    norm, index = _normalized(text)
    for category, pattern in _PHRASES:
        for m in pattern.finditer(norm):
            if m.end() <= m.start():
                continue
            if category == "data_exfiltration" and m.group(0).lower().startswith(
                    ("user passwords", "api keys", "access tokens", "private keys")):
                # "user passwords" alone is ordinary text ("list all passwords policies");
                # it is an attack only as the object of a request verb in the same sentence.
                sentence_start = max(norm.rfind(".", 0, m.start()), norm.rfind("\n", 0, m.start())) + 1
                if not _EXFIL_VERB.search(norm[sentence_start:m.start()]):
                    continue
            spans.append((index[m.start()], index[m.end() - 1] + 1, category))
    return spans


def _encoded_spans(text):
    spans = []
    for m in _BASE64.finditer(text):
        token = m.group(0)
        if len(token) % 4:
            continue
        try:
            decoded = base64.b64decode(token, validate=True).decode("utf-8")
        except (binascii.Error, UnicodeDecodeError, ValueError):
            continue
        if sum(ch.isprintable() or ch.isspace() for ch in decoded) < 0.95 * len(decoded):
            continue
        if _phrase_spans(decoded) or _SHELL.search(decoded):
            spans.append((m.start(), m.end(), "encoded_payload"))
    return spans


def _attack_spans(text):
    spans = _phrase_spans(text) + _encoded_spans(text)
    for category, pattern in (("hidden_content", _HIDDEN_HTML),
                              ("markdown_image_exfiltration", _MARKDOWN_IMAGE_EXFIL),
                              ("command_injection", _SHELL),
                              ("chat_template_tokens", _CHAT_TOKENS)):
        spans.extend((m.start(), m.end(), category) for m in pattern.finditer(text))
    spans.sort()
    merged = []
    for start, end, category in spans:
        if merged and start < merged[-1][1]:
            prev = merged[-1]
            merged[-1] = (prev[0], max(prev[1], end), prev[2])
        else:
            merged.append((start, end, category))
    return merged


def find_prompt_attacks(text):
    """Attack categories found in *text* (empty list: none)."""
    if not isinstance(text, str) or not text:
        return []
    return sorted({category for _s, _e, category in _attack_spans(text)})


def sanitize_prompt(text):
    """*text* with prompt-injection spans replaced by a marker; anything else unchanged."""
    if not isinstance(text, str) or not text:
        return text
    out = text
    for start, end, category in reversed(_attack_spans(text)):
        out = out[:start] + "<prompt_injection_removed: " + category + ">" + out[end:]
    return out


def sanitize_messages(messages, roles=("user", "tool", "function")):
    """A copy of a chat message list with ``sanitize_prompt`` applied to the given roles.

    Handles string content and lists of content parts (``{"type": "text", "text": ...}``).
    System and assistant turns are the application's own text and are left as they are."""
    if not isinstance(messages, list):
        return messages
    result = []
    for message in messages:
        if isinstance(message, dict) and message.get("role") in roles:
            message = dict(message)
            content = message.get("content")
            if isinstance(content, str):
                message["content"] = sanitize_prompt(content)
            elif isinstance(content, list):
                parts = []
                for part in content:
                    if isinstance(part, dict) and isinstance(part.get("text"), str):
                        part = dict(part, text=sanitize_prompt(part["text"]))
                    parts.append(part)
                message["content"] = parts
        result.append(message)
    return result


# --- PII --------------------------------------------------------------------
# What is personal data is defined by the policy: callers pass the violated
# policy's ``runtime.routine.params.categories`` (the scanner writes them into
# each call). There is no default set. The category names are the policy
# vocabulary of the tenant's enabled PII policies (AI_DAT_SEC_011, 012, 023). A
# category with no text detector here (ethnicity, biometrics, the secret types
# of 011) is not redacted; ``unsupported_pii_categories`` lists them so the
# scanner can say so in the PR.

def _luhn(digits):
    total, parity = 0, len(digits) % 2
    for i, ch in enumerate(digits):
        d = int(ch)
        if i % 2 == parity:
            d *= 2
            if d > 9:
                d -= 9
        total += d
    return total % 10 == 0


def _is_card(value):
    digits = re.sub(r"\D", "", value)
    return 13 <= len(digits) <= 19 and digits[0] in "23456" and len(set(digits)) > 1 and _luhn(digits)


_STREET = (r"(?:Street|St|Avenue|Ave|Road|Rd|Boulevard|Blvd|Lane|Ln|Drive|Dr|Court|Ct|Way|Place|Pl"
           r"|Terrace|Parkway|Pkwy|Highway|Hwy)\.?")
_DATE = r"(?:\d{4}-\d{2}-\d{2}|\d{1,2}/\d{1,2}/\d{2,4})"
_NUM = r"(?:\s*(?:no\.?|number|num|#|id))?\s*[:#=]?\s*"
_OCTET = r"(?:25[0-5]|2[0-4]\d|1\d\d|[1-9]?\d)"
_CODE = r"(?=[A-Z0-9-]*\d)[A-Z0-9-]{%d,%d}\b"


def _labelled(label, value, flags=re.I):
    """Pattern that keeps *label* and masks the value after it."""
    # The label is always case-insensitive; *flags* apply to the value (names keep their capitals).
    return re.compile(r"(?P<label>\b(?i:" + label + r")(?i:" + _NUM + r"))" + value, flags)


# policy category -> patterns; a pattern with a "label" group keeps the label.
_DETECTORS = {
    "email": (re.compile(r"(?<![\w.+-])[A-Za-z0-9._%+-]+@[A-Za-z0-9-]+(?:\.[A-Za-z0-9-]+)*\.[A-Za-z]{2,}(?![\w-])"),),
    "credit_card": (re.compile(r"(?<![\w-])\d{4}(?:[ -]?\d{4}){2}[ -]?\d{1,7}(?![\w-])"),),
    "financial_account_number": (
        re.compile(r"\b[A-Z]{2}\d{2}(?:\s?[A-Z0-9]{4}){3,7}(?:\s?[A-Z0-9]{1,3})?\b"),
        _labelled(r"(?:bank\s+|checking\s+|savings\s+)?(?:account|acct|a/c)|routing|IBAN", _CODE % (6, 34))),
    "ssn": (re.compile(r"(?<![\w-])\d{3}-\d{2}-\d{4}(?![\w-])"),
            _labelled(r"SSN|social\s+security", r"\d{3}\s\d{2}\s\d{4}\b")),
    "taxpayer_id": (_labelled(r"tax(?:payer)?\s*id(?:entification)?|EIN|TIN", _CODE % (8, 15)),),
    "passport_number": (_labelled(r"passport", r"(?=[A-Z0-9]*\d)[A-Z0-9]{6,9}\b"),),
    "drivers_license_number": (_labelled(r"driver'?s?\s+licen[cs]e|DL", _CODE % (5, 20)),),
    "medical_records": (_labelled(r"MRN|medical\s+record|patient\s+id", _CODE % (4, 20)),),
    "employee_id": (_labelled(r"employee|emp|staff", _CODE % (3, 20)),),
    "school_id": (_labelled(r"student|school", _CODE % (3, 20)),),
    "vehicle_identification_number": (_labelled(r"VIN|vehicle\s+identification", r"[A-HJ-NPR-Z0-9]{17}\b"),),
    "mac_address": (re.compile(r"(?<![\w:-])(?:[0-9A-Fa-f]{2}[:-]){5}[0-9A-Fa-f]{2}(?![\w:-])"),),
    "ip_address": (re.compile(r"(?<![\w.])(?<!v)(?:" + _OCTET + r"\.){3}" + _OCTET + r"(?![\w.])"),
                   re.compile(r"(?<![\w:])(?:[0-9A-Fa-f]{1,4}:){7}[0-9A-Fa-f]{1,4}(?![\w:])")),
    "fine_location": (_labelled(r"lat(?:itude)?|gps|location|coord(?:inate)?s?",
                                r"-?\d{1,3}\.\d{4,},\s*-?\d{1,3}\.\d{4,}\b"),),
    "year_of_birth": (_labelled(r"DOB|D\.O\.B\.?|date\s+of\s+birth|born\s+on|birth\s*date", _DATE),
                      _labelled(r"born\s+in|year\s+of\s+birth|birth\s+year", r"(?:19|20)\d{2}\b")),
    "birthplace": (_labelled(r"place\s+of\s+birth|birth\s*place", r"[A-Z][A-Za-z'.-]+(?:[ ,]+[A-Z][A-Za-z'.-]+){0,3}", 0),),
    "mothers_maiden_name": (_labelled(r"mother'?s\s+maiden\s+name(?:\s+is)?", r"[A-Z][A-Za-z'-]+(?:\s[A-Z][A-Za-z'-]+)?", 0),),
    "phone": (re.compile(r"(?<![\w+(])(?:\+\d{1,3}[\s.-]?)?(?:\(\d{3}\)\s?|\d{3}[\s.-])\d{3}[\s.-]\d{4}(?![\w-])"),
              re.compile(r"(?<![\w+])\+\d{1,3}[\s.-]?\d{2,5}(?:[\s.-]?\d{2,5}){1,3}(?![\w-])"),
              _labelled(r"phone|mobile|cell|tel|telephone|fax", r"\+?\d[\d\s().-]{6,}\d\b")),
    "home_address": (re.compile(r"\b\d{1,6}\s+(?:[A-Z][a-z]+\s){1,3}" + _STREET
                                + r"(?:,\s*[A-Z][a-z]+(?:\s[A-Z][a-z]+)*)?(?:,\s*[A-Z]{2}(?:\s+\d{5}(?:-\d{4})?)?)?"),),
}
# Applied in this order (dict order): longer, more specific shapes first (a card before a phone).


def _normalized_categories(categories):
    if isinstance(categories, str):
        categories = (categories,)
    if not categories:
        return ()
    return tuple(str(c).strip().lower() for c in categories if str(c).strip())


def unsupported_pii_categories(categories):
    """The policy categories this guard has no text detector for (they are not redacted)."""
    return [c for c in _normalized_categories(categories) if c not in _DETECTORS]


def _masker(category):
    def mask(match):
        if category == "credit_card" and not _is_card(match.group(0)):
            return match.group(0)
        label = match.groupdict().get("label") or ""
        return label + "<redacted:" + category + ">"
    return mask


# mask_pii: one fixed label per category (the policy's display vocabulary); identifiers
# keep their last 4 digits.
_MASK_LABEL = {
    "phone": "phone", "email": "email", "home_address": "address", "year_of_birth": "dob",
    "passport_number": "passport", "drivers_license_number": "drivers_license", "taxpayer_id": "tax_id",
    "employee_id": "employee_id", "school_id": "school_id", "vehicle_identification_number": "vin",
    "ip_address": "ip_address", "mac_address": "mac_address", "birthplace": "birthplace",
    "mothers_maiden_name": "maiden_name", "medical_records": "medical", "fine_location": "location",
}
_KEEP_LAST4 = frozenset({"ssn", "credit_card", "financial_account_number"})


def _last4(value):
    digits = [i for i, ch in enumerate(value) if ch.isdigit()]
    keep = set(digits[-4:])
    return "".join(ch if (not ch.isalnum() or i in keep) else "*" for i, ch in enumerate(value))


def _display_masker(category):
    def mask(match):
        if category == "credit_card" and not _is_card(match.group(0)):
            return match.group(0)
        label = match.groupdict().get("label") or ""
        value = match.group(0)[len(label):]
        if category in _KEEP_LAST4:
            return label + _last4(value)
        return label + "<masked:" + _MASK_LABEL.get(category, category) + ">"
    return mask


def _structured(value, fn, depth=0):
    """*fn* applied to every string inside *value*, keeping its type: lists, tuples, sets,
    dicts, pydantic models (v1 and v2) and dataclasses come back as the same type with
    their text fields masked; anything else is returned unchanged."""
    if isinstance(value, str):
        return fn(value)
    if depth > 8 or value is None or isinstance(value, (bytes, bytearray, int, float, bool)):
        return value
    if isinstance(value, dict):
        return type(value)((k, _structured(v, fn, depth + 1)) for k, v in value.items()) \
            if type(value) is not dict else {k: _structured(v, fn, depth + 1) for k, v in value.items()}
    if isinstance(value, (list, tuple, set, frozenset)):
        items = [_structured(v, fn, depth + 1) for v in value]
        if isinstance(value, tuple) and hasattr(value, "_fields"):  # namedtuple
            return type(value)(*items)
        return type(value)(items)
    fields = getattr(type(value), "model_fields", None)  # pydantic v2
    if isinstance(fields, dict) and hasattr(value, "model_copy"):
        return value.model_copy(update={f: _structured(getattr(value, f, None), fn, depth + 1) for f in fields})
    fields = getattr(type(value), "__fields__", None)  # pydantic v1
    if isinstance(fields, dict) and hasattr(value, "copy"):
        return value.copy(update={f: _structured(getattr(value, f, None), fn, depth + 1) for f in fields})
    import dataclasses
    if dataclasses.is_dataclass(value) and not isinstance(value, type):
        return dataclasses.replace(value, **{f.name: _structured(getattr(value, f.name), fn, depth + 1)
                                             for f in dataclasses.fields(value) if f.init})
    return value


def mask_pii(text, categories):
    """*text* with the personal data of the given policy *categories* masked for display:
    identifiers keep their last 4 digits, other values become ``<masked:label>``. *text*
    may also be a list, dict, pydantic model or dataclass (e.g. response sources): the same
    type comes back with every text field masked."""
    if not isinstance(text, str):
        return _structured(text, lambda t: mask_pii(t, categories)) if text is not None else text
    if not text:
        return text
    wanted = set(_normalized_categories(categories))
    out = text
    for category, patterns in _DETECTORS.items():
        if category in wanted:
            for pattern in patterns:
                out = pattern.sub(_display_masker(category), out)
    return out


def redact_pii(text, categories):
    """*text* with the personal data of the given policy *categories* replaced by
    ``<redacted:category>``; anything else unchanged.

    *categories* is the violated policy's ``runtime.routine.params.categories``
    (e.g. ``("ssn", "email", "phone", ...)``); only those are redacted. *text* may also be
    a list, dict, pydantic model or dataclass: the same type comes back redacted."""
    if not isinstance(text, str):
        return _structured(text, lambda t: redact_pii(t, categories)) if text is not None else text
    if not text:
        return text
    wanted = set(_normalized_categories(categories))
    out = text
    for category, patterns in _DETECTORS.items():
        if category in wanted:
            for pattern in patterns:
                out = pattern.sub(_masker(category), out)
    return out


# --- model output: dynamic code execution -------------------------------------

_CODE_EXECUTION = (
    ("python_eval_exec", re.compile(r"(?<![\w.])(?:eval|exec|compile|__import__)\s*\(")),
    ("os_command", re.compile(r"\bos\.(?:system|popen|exec[lv]p?e?|spawn[lv]p?e?)\s*\(")),
    ("subprocess_shell", re.compile(r"\bsubprocess\.\w+\s*\([^)]*shell\s*=\s*True", re.S)),
    ("js_eval", re.compile(r"(?<![\w.])(?:eval|new\s+Function|Function)\s*\(")),
    ("js_child_process", re.compile(r"\b(?:child_process\.)?(?:exec|execSync|spawn|spawnSync)\s*\(\s*['\"`]")),
    ("shell_eval", re.compile(r"(?:^|[;&|\s])(?:eval|source)\s+['\"$]|\b(?:bash|sh|zsh)\s+-c\s+\S", re.M)),
    ("pipe_to_shell", re.compile(r"\b(?:curl|wget)\b[^\n|]*\|\s*(?:sudo\s+)?(?:ba|z)?sh\b")),
    ("destructive_command", re.compile(r"\brm\s+-rf\s+/|\bmkfs(?:\.\w+)?\s|\bdd\s+if=|:\(\)\s*\{\s*:\|:&\s*\};:")),
)


def find_code_execution(text):
    """The dynamic code-execution primitives found in *text* (empty list: none).

    For model output that is executed, written to disk or shown as runnable code:
    the caller decides what to do with a finding (refuse, flag, or require review);
    this function never changes the text."""
    if not isinstance(text, str) or not text:
        return []
    return sorted({name for name, pattern in _CODE_EXECUTION if pattern.search(text)})


# --- uploaded file content: shell commands ---------------------------------------

_CMD = (
    r"(?:sudo\s+)?(?:"
    r"alias\s+[\w.-]+=\S*"
    r"|(?:rg|ripgrep)\s+[-\w'\"./*]+"
    r"|curl\s+(?:-\S+\s+)*\S+"
    r"|wget\s+(?:-\S+\s+)*\S+"
    r"|rm\s+(?:-[a-z]+\s+)*[\w./~*$-]+"
    r"|echo\s+[^\n>]*>>?\s*\S+"
    r"|dd\s+(?:if|of)=\S+"
    r"|git\s+(?:clone|push|pull|fetch|reset|checkout|remote|config|rm|apply|am)\b[^\n]*"
    r"|tar\s+-?[a-z]*[xcz][a-z]*f?\s+\S+"
    r"|chmod\s+(?:-[a-z]+\s+)*[0-7ugoa+=,rwxst-]+\s+\S+"
    r"|chown\s+(?:-[a-z]+\s+)*[\w.:-]+\s+\S+"
    r"|fsck(?:\.\w+)?(?:\s+-\S+)*\s+\S+"
    r"|mkfs(?:\.\w+)?\s+\S+"
    r"|shred\s+(?:-\S+\s+)*\S+"
    r"|(?:eval|source)\s+\S+"
    r"|export\s+[A-Z_][A-Z0-9_]*=\S*"
    r")"
)
# A command at the start of a line, after a prompt, or after a shell separator.
_SHELL_LINE = re.compile(r"(?:(?<=^)|(?<=\n)|(?<=[;&|`]))[ \t]*(?:[$#>]\s*)?" + _CMD + r"[^\n;&|]*", re.I)
_BASE64_SHORT = re.compile(r"(?<![A-Za-z0-9+/=])[A-Za-z0-9+/]{12,}={0,2}(?![A-Za-z0-9+/=])")
_LEET_MULTI = (("|-|", "h"), ("|_|", "u"), ("|<", "k"), ("|\\|", "n"), ("/\\", "a"), ("()", "o"))


def _fold_leet(line):
    for seq, ch in _LEET_MULTI:
        line = line.replace(seq, ch)
    return line.translate(_LEET)


def _shell_spans(text):
    """(start, end) of shell-command lines in *text*: plain, leetspeak-folded per line, or
    inside a base64 token."""
    spans = [(m.start(), m.end()) for m in _SHELL_LINE.finditer(text)]
    offset = 0
    for line in text.splitlines(keepends=True):
        body = line.rstrip("\r\n")
        folded = _fold_leet(body)
        if folded != body and _SHELL_LINE.search(folded) and not _SHELL_LINE.search(body):
            lead = len(body) - len(body.lstrip())
            spans.append((offset + lead, offset + len(body)))
        offset += len(line)
    for m in _BASE64_SHORT.finditer(text):
        token = m.group(0)
        if len(token) % 4:
            continue
        try:
            decoded = base64.b64decode(token, validate=True).decode("utf-8")
        except (binascii.Error, UnicodeDecodeError, ValueError):
            continue
        if _SHELL_LINE.search(decoded):
            spans.append((m.start(), m.end()))
    spans.sort()
    merged = []
    for start, end in spans:
        if merged and start <= merged[-1][1]:
            merged[-1] = (merged[-1][0], max(merged[-1][1], end))
        else:
            merged.append((start, end))
    return merged


def find_shell_commands(text):
    """The shell-command lines found in uploaded or fetched content (empty list: none)."""
    if not isinstance(text, str) or not text:
        return []
    return [text[s:e].strip() for s, e in _shell_spans(text)]


def remove_suspicious_content(text):
    """*text* (uploaded or fetched file content) with each shell command replaced by
    ``<suspicious_content_removed>``; the rest of the content is kept."""
    if not isinstance(text, str):
        return _structured(text, remove_suspicious_content) if text is not None else text
    out = text
    for start, end in reversed(_shell_spans(text)):
        out = out[:start] + "<suspicious_content_removed>" + out[end:]
    return out
